In [2]:
#load the train dataset - tiny shakespeare
!curl -L https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt -o input.txt


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1089k  100 1089k    0     0  4760k      0 --:--:-- --:--:-- --:--:-- 4777k


In [3]:
#read the data
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [4]:
print('lengt of the file', len(text))

lengt of the file 1115394


In [5]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [6]:
chars = sorted(set(text))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [7]:
stoi = { c:i for i, c in enumerate(chars) }
itos = { i:c for i, c in enumerate(chars)}
s : str
encode = lambda s : [ stoi[x] for x in s] #encoder: Take a string and convert it do an integer 
it : list
decode  = lambda it : ''.join([itos[x] for x in it]) #decoder: take a list of integers, returns a string

print(encode('Frank the tank'))
print(decode(encode('Frank the tank')))

[18, 56, 39, 52, 49, 1, 58, 46, 43, 1, 58, 39, 52, 49]
Frank the tank


In [8]:
#encode the complete text
import torch
data : torch.tensor = torch.tensor(encode(text), dtype=torch.long)
print(data.shape)
print(data[:100])

torch.Size([1115394])
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [9]:
#split of train and val data
n = int(0.9 * (len(data)))
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [11]:
batch_size : int = 4 #number of parallel blocks 
block_size : int = 8 #number of characters per block
torch.manual_seed(1337)
def get_batch(split: str) -> tuple[torch.tensor, torch.tensor] : 
    data = train_data if split == 'train' else val_data
    ix : torch.tensor = torch.randint(len(data)-batch_size, (batch_size,))
    x : torch.Tuple[torch.Tensor, ] = torch.stack([data[i:i+block_size] for i in ix ])
    y : torch.Tuple[torch.Tensor, ] =  torch.stack([data[i+1:i+block_size+1] for i in ix ])
    return x, y
get_batch('val')

(tensor([[26, 16, 13, 10,  0, 27,  1, 42],
         [63,  6,  1, 57, 47, 56, 10,  0],
         [ 1, 46, 43, 56,  6,  0,  5, 41],
         [43, 63,  1, 40, 53, 53, 58,  7]]),
 tensor([[16, 13, 10,  0, 27,  1, 42, 43],
         [ 6,  1, 57, 47, 56, 10,  0, 57],
         [46, 43, 56,  6,  0,  5, 41, 59],
         [63,  1, 40, 53, 53, 58,  7, 46]]))

In [12]:
xb, yb = get_batch('train')
print(f'inputs: {xb.shape}')
print(xb)
print(f'targets: {yb.shape}')
print(yb)

for batch in range(batch_size): #batch dimension
    for t in range(block_size): # time dimension
        context = xb[batch, :t+1]
        print(f'input {context.tolist()} target is {yb[batch,t]}')


inputs: torch.Size([4, 8])
tensor([[43,  1, 39, 52,  1, 47, 52, 41],
        [53, 58, 46,  1, 40, 59, 56, 52],
        [53,  1, 40, 43,  1, 63, 53, 59],
        [ 1, 56, 43, 45, 39, 56, 42,  8]])
targets: torch.Size([4, 8])
tensor([[ 1, 39, 52,  1, 47, 52, 41, 46],
        [58, 46,  1, 40, 59, 56, 52,  8],
        [ 1, 40, 43,  1, 63, 53, 59, 56],
        [56, 43, 45, 39, 56, 42,  8,  0]])
input [43] target is 1
input [43, 1] target is 39
input [43, 1, 39] target is 52
input [43, 1, 39, 52] target is 1
input [43, 1, 39, 52, 1] target is 47
input [43, 1, 39, 52, 1, 47] target is 52
input [43, 1, 39, 52, 1, 47, 52] target is 41
input [43, 1, 39, 52, 1, 47, 52, 41] target is 46
input [53] target is 58
input [53, 58] target is 46
input [53, 58, 46] target is 1
input [53, 58, 46, 1] target is 40
input [53, 58, 46, 1, 40] target is 59
input [53, 58, 46, 1, 40, 59] target is 56
input [53, 58, 46, 1, 40, 59, 56] target is 52
input [53, 58, 46, 1, 40, 59, 56, 52] target is 8
input [53] target i

In [13]:
from torch.nn import functional as F
import torch.nn as nn
torch.manual_seed(1337)

In [14]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size : int, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        #like in makemore each letter and the probality of the next token is stored in the embedding
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    
    def forward(self, idx, targets=None):
#        print(f'idx.shape: {idx.shape}, targets.shape: {targets.shape}')
        logits = self.token_embedding_table(idx) #B-Batch, T - Time, C - Channel
        #print('logits:', logits)
        #why C - 65 ? This a are the class probalities for a certain character
        #logits has 4B, 8T, 65C <> Targets is 4B, 8T
        if(targets is None):
            loss=None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
    #        print(logits.shape)
    #        print('targets', targets)
            targets = targets.view(B*T)

    #        print(targets.shape)
    #        print(targets)
            loss = F.cross_entropy(logits, targets)
#        print(loss)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        #idx is (B,T) array of indicies in the current context
        for i in range(max_new_tokens):
            #predict the next tokens
            logits, loos = self(idx)
            #after prediction select the most proably next token. We use Softmax for prediction
            #focus on the last time step
            #print(f'logits shape: {logits.shape}')
            logits = logits[:,-1,:] #becomes (B,C)
            #print(f'After trans logits shape: {logits.shape}')
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            #append sampled index to the running contect
            idx = torch.cat((idx, idx_next), dim=1) #(B, B+1)
        return idx            

In [15]:
m = BigramLanguageModel(vocab_size)
out = m(xb, yb)


In [16]:
testembed = nn.Embedding(10, 3)

In [17]:
testtorch = torch.LongTensor([9,1,2,3,5,6,4,2,1,4,5,])
testembed(testtorch)

tensor([[-0.8646, -0.0317, -1.1180],
        [ 0.5374,  0.4829, -1.1658],
        [-0.8079, -1.3601, -0.7062],
        [-0.2335,  0.0975,  2.1706],
        [-1.5548, -0.1463,  0.2918],
        [-0.1257,  0.0723, -0.2567],
        [ 0.7908, -0.4123,  0.2283],
        [-0.8079, -1.3601, -0.7062],
        [ 0.5374,  0.4829, -1.1658],
        [ 0.7908, -0.4123,  0.2283],
        [-1.5548, -0.1463,  0.2918]], grad_fn=<EmbeddingBackward0>)

In [18]:

next_tokens = m.generate(xb,2)
print(xb.shape)
print(next_tokens.shape)
print(next_tokens[1,:])
print(decode(next_tokens[1,:].tolist()))


torch.Size([4, 8])
torch.Size([4, 10])
tensor([53, 58, 46,  1, 40, 59, 56, 52, 17,  9])
oth burnE3


In [19]:
next_tokens = m.generate(torch.zeros(1,1, dtype=torch.long),100)
print(decode(next_tokens[0].tolist()))


F$ !RjuYCeKpwwoiNmmnZvfTX&
pmonzO'lvmZ N
3S!3fEHAXmrEXIJMHAab&et:xItRQb
P&Z;?uHkVtUAAJ&yh zPkSruSPyN


In [20]:
optimzer : torch.optim.AdamW= torch.optim.AdamW(m.parameters(), lr=1e-3)

In [21]:
batch_size = 32
for steps in range(1000):
    #sample a batch of data
    xb, yb = get_batch('train')
    logits, loss = m(xb, yb)
    
    optimzer.zero_grad(set_to_none=None)
    loss.backward()
    optimzer.step()
    
print(loss.item())
    

3.722606658935547


In [22]:
next_tokens = m.generate(torch.zeros(1,1, dtype=torch.long),100)
print(decode(next_tokens[0].tolist()))


VXa-
reQdumZJ&$EGK'gUgduwKoRjP
SiAV'otsEQcP,pru .yltoHEzzJNvkIs
3siq-LEq$VOprsrd&l,Ngdd?oQ3k'TERyiyW


In [23]:
for i in m.parameters():
    print(i.shape)


torch.Size([65, 65])


In [24]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x : torch.tensor = torch.randn((B,T,C))
x.shape

torch.Size([4, 8, 2])

In [25]:
xbow = torch.zeros(B,T,C)
for b in range(B):
    for t in range(T):
        print(f't{t}, b{ b }')
        xprev = x[b,:t+1]
        print(xprev)
        xbow[b,t] = torch.mean(xprev, 0) 
        print(torch.mean(xprev, 0) )
        print(xbow[b,t])
        print('-'*10)

t0, b0
tensor([[ 0.1808, -0.0700]])
tensor([ 0.1808, -0.0700])
tensor([ 0.1808, -0.0700])
----------
t1, b0
tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152]])
tensor([-0.0894, -0.4926])
tensor([-0.0894, -0.4926])
----------
t2, b0
tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255]])
tensor([ 0.1490, -0.3199])
tensor([ 0.1490, -0.3199])
----------
t3, b0
tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643]])
tensor([ 0.3504, -0.2238])
tensor([ 0.3504, -0.2238])
----------
t4, b0
tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679]])
tensor([0.3525, 0.0545])
tensor([0.3525, 0.0545])
----------
t5, b0
tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102]])
tensor([ 0.0688, -0.0396])
tensor([ 0.0688,

In [26]:
xbow

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [49]:
nn.Embedding(6,1)(torch.arange(4).unsqueeze(dim=0))


tensor([[[ 2.3363],
         [-1.2584],
         [ 1.2859],
         [-0.0518]]], grad_fn=<EmbeddingBackward0>)